[pytest]
log_cli=true
# Показывать логи в терминале при запуске тестов
log_level = INFO
# Минимальный уровень логов для вывода в консоль (INFO и выше)
log_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
# Формат строки лога
log_date_format = %Y-%m-%d %H:%M:%S
# Формат даты/времени в логах
log_file_level = DEBUG
# Минимальный уровень логов для записи в файл (если используется log_file)

addopts = -v --tb=short

log_file = test.log

pythonpath = .
